# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test the application
        run: yarn test

      - name: Build the application
        run: yarn build

      - name: Build the package
        run: |
          npm pack ./dist/zxing-scanner
          mv sondreb-ngx-scanner-*.tgz ./package.tgz

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pack-artifact
          path: ./package.tgz

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: pack-artifact

      - name: List artifact contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Listing current directory:"
          ls -la ./
          echo "Recursively listing all files:"
          find . -type f -ls

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org/

      - run: npm publish ./package.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
